Feature - More Screen and Logout
ksookdhew/F1-Pet-Project pull request #39
Opened 2024-05-27 14:27 UTC by ksookdhew

## Description
Added the more screen, logout functionality and bug fixes

## Checklist 
Please review and check the following before submitting this pull request: 
- [x] The code follows the project's coding standards. 
- [x] 100% Unit test coverage for View Models 
- [x] All warnings Resolved.

2024-05-27 14:28 UTC, ksookdhew commented on F1/F1/More/MoreViewController.swift
> +           let sceneDelegate = windowScene.delegate as? SceneDelegate {
indentation

2024-05-27 14:49 UTC, kiasha10 approved these changes

2024-05-28 07:13 UTC, sjacobs1 submitted a review, later dismissed

2024-05-28 08:33 UTC, kieran-woodrow requested changes

2024-05-28 08:33 UTC, kieran-woodrow commented on F1/F1/Login/LoginViewController.swift
>      @IBAction func loginAction(_ sender: Any) {
private

2024-05-28 12:11 UTC, kieran-woodrow approved these changes

2024-05-28 12:14 UTC, kiasha10 approved these changes

2024-05-28 12:16 UTC, merged